src/InputNumber.js

现在对于没有 defaultValue 的输入框，一开始输入非数字字符，可以键入。
对于非法数字字符，应始终置空。

invalid value should set empty text in input

---

src/InputNumber.js

Fix.
```bash
warning.js:44Warning: Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). 
Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
```

fix: should work with React@0.15.0

---

src/index.js
src/index.web.js
tests/index.js

There were bugs with the readOnly propery: we could still step up and down. This fixes it.
NOTE: I'm not sure how to properly test the ReactNative code.

Handle readOnly properly

---

examples/react-native/demo.js
src/index.ios.js

Added new optional prop keyboardType. Changed onBlur to onEndEditing for Android support. The onBlur event object on Android doesn't contain the expected text property, onEndEditing's event object does.

Fixed crash on Android on textInput blur. Added optional prop keyboardType.

---

src/index.js
tests/index.js

close #48
close ant-design/ant-design-mobile/issues/891

fix: split TouchEvents amd MouseEvents

---

README.md
examples/combination-key-format.html
examples/combination-key-format.js
src/index.js
src/mixin.js
tests/index.js

1、support of ctrl and shift key which could +10, +0.1 times of step          
2、simple formatter, with the function eg:          
```
format (num) {
return "$ "+ num
}
```
3、bug fix, the value still changes when pressing up or down key even with the readonly status
Thanks, Sincerely
Jiramew

support of ctrl and shift key & simple formatter

---

README.md
examples/combination-key-format.js
src/index.js
src/mixin.js
tests/index.js

Add parser to extract value from format. 
Default parser will be:
```js
string.replace(/[^\w\.-]*/g, '') 
```
fix https://github.com/ant-design/ant-design/pull/5178
Thanks so much
Jiramew

add format parser

---

src/mixin.js
tests/index.js

close #52 
```js
expect(getPrecision(1e-9)).toBe(-9) // wrong
expect(getPrecision(1e-9)).toBe(9) // right
```

fix: precision

---

src/index.js
src/mixin.js

There was an issue at https://github.com/ant-design/ant-design/issues/5303.
The problem is as follows
- When testing on http://regexr.com, the regex expression at https://github.com/react-component/input-number/blob/master/src/mixin.js#L5 did not work as expected.
- The number could not be deleted if the formatter is exist.

UX improvements when formatter exist

---

src/mixin.js

修改 mixin.js 第175行的判断，使 this.props.precision 传入值为 0 的时候也能生效。

fix issue: #72

---

src/index.js

add props support of tabIndex , and the default props of tabIndex are the '0'，tabindex="0" means that the element should be focusable in sequential keyboard navigation, but its order is defined by the document's source order.

feat: add support of tabIndex

---

src/index.js

Previously, `getValidValue(value)` compared `value` to the current prop's `min` and `max`. However, it is called in 'componentWillReceiveProps', so `getValidValue(value)` compared nextProp's `value` to current prop's `min` and `max`. This is incorrect -- it should compare nextProp's `value` to nextProp's `min` and `max`.
Add `min` and `max` parameters  to getValidValue() function, with default values of `this.props.min` and `this.props.max`

Fix getValidValue function

---

assets/index.less

Using Chrome -
Before:
After:
Thanks for the great package!

Minor visual changes to align the bottom and side bars with the input

---

src/index.js
tests/index.js

Allows for `data-*`, `aria-*`, and `role` props to be passed to the rendered input.

Pass data-*, aria-* and role props to the input

---

.eslintrc
src/index.js

1. Fix https://github.com/ant-design/ant-design/issues/10663; The problem is setSelection does not automatically focus the input element
2. Add eslint, let editor can fix styles and detect errors automatically.
3. Fix the cursor problem in increase; for example `9<cursor/>` after increase will become `1<cursor/>0`;  In this PR, we will let setSelection happens when and only when the selection is expanded

Fix focus shown in ant-design #10663

---

src/index.js

ref #https://github.com/ant-design/ant-design/issues/12808

fix InputNumber在父页面组件update并re-render的时候，会失去自身之前的数字选中状态

---

src/index.js

Apparently, using `autoComplete` with capital C is not recognized by Chrome as well as the `"off"` value. This is why I am proposing to make the autocomplete attribute customizable in order to be able to apply a workaround that works for me. Something like this `autocomplete="no"`.

Autocomplete attribute customizable

---

src/index.js
tests/index.js

fixes #120 
I added a check in `componentWillReceiveProps` that ensures that the value changed

fix input value resetting when parent rerenders with the same value

---

src/index.js
tests/index.js

Fix https://github.com/ant-design/ant-design/issues/14277

FIx InputNumber displays min value when min is > 0 and value is null

---

package.json
src/index.js
tests/index.js

I noticed that everytime I enter in a number with a period followed by trailing 0's, I would be getting a string back which would trip up my validation on the ANTD side of things.
For example:
Input: '1.0000'
Value to be displayed: '1.0000'
Value to be returned from onChange function: 1
however what I was getting was:
Input: '1.0000'
Value to be displayed: '1.0000'
Value to be returned from onChange function: '1.00'
in which the validation would pick it up as not a number and show an error message while I was in focus of the component. It was fixed when I stopped focusing on the component but having '1.00 is not a number' is incorrect behaviour.
My change fixes that and now numbers with a decimal + trailing 0's are considered valid numbers. They are displayed properly and returned to the …

Fixed invalidation of a number with a period + trailing 0's

---

src/index.js
tests/index.js

Replace toFixed() by Math.round(), because toFixed() follow Banker's Round
https://blog.csdn.net/fjnpysh/article/details/79077997

chore: Use Math.round other than toFixed

---

src/index.js

This pr fixes a bug, where the title prop never gets added to the actual input.
Here's the original issue (from ant-design) where this was discovered: https://github.com/ant-design/ant-design/issues/13410

Pass the `title` prop down to the actual input

---

src/index.js

@afc163  之前在每次渲染后都将`pressingUpOrDown`设为`false`,导致触发`input`事件后，按住向上箭头时，在执行下面代码的时候：
``` js
if (!isEqual(prevProps.value, value) ||
!isEqual(prevProps.max, max) ||
!isEqual(prevProps.min, min)) {
const validValue = focused ? value : this.getValidValue(value);
let nextInputValue;
if (this.pressingUpOrDown) {
nextInputValue = validValue;
} else if (this.inputting) {
nextInputValue = this.rawInput;
} else {
nextInputValue = this.toPrecisionAsStep(validValue);
}
this.setState({ // eslint-disable-line
value: validValue,
inputValue: nextInputValue,
});
}
```
取的是`rawInput`的值（可能是由于渲染的问题，渲染一次后下次再取`pressingUpOrDown`的时候就成为了`false`，但是如果不按住箭头的话就没有问题，这个原因我还没有查明白）
现在我把`this.pressingUpOrDown = false`放在`step`方法的最后`setState`的回调里面，效果和之前应该是相同的，不知道有什么问题？ …

fix: autoStep is not work after triggering input event(#22528)

---

src/index.js
tests/index.js

- Someone like me might need to pass `onPaste` handler to input.
- Destructuring `onPaste` from props and pass it to input dom.

Add onPaste prop 

---

src/InputNumber.tsx
tests/index.test.js

... to tell the source of the value change
In certain scenarios, such as Yuque Show, value changes are only necessary to handle in following cases:
- enter pressed
- blurred
- value stepped by clicking or pressing up/down arrow
props.onChange triggers too often since any temporary edits change value.

feat: trigger props.onStep when value stepps up/down

---

src/InputNumber.tsx
tests/index.test.js

...remove the unnecessary `Number()` conversion

fix: don't override formatted value when blur

---

src/InputNumber.tsx
tests/index.test.js

Fixes [#28366](https://github.com/ant-design/ant-design/issues/28366)

fix: caret position when last string exists

---

docs/examples/simple.tsx
src/InputNumber.tsx
src/interface.ts
tests/index.test.js

fix https://github.com/ant-design/ant-design/issues/15682
@zombieJ @afc163

feat: onKeyDown support preventDefault

---

src/hooks/useLayoutEffect.ts
src/hooks/useUpdateEffect.ts

fix the `useLayoutEffect` warning of `nextjs`：
`
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
`
close #302

feat(useUpdateEffect): support ssr

---

src/utils/MiniDecimal.ts
tests/decimal.test.tsx
tests/util.test.tsx

resolve ant-design/ant-design#29754

fix: unable to empty value when setting precision

---

src/InputNumber.tsx
tests/decimal.test.tsx

Fix ant-design/ant-design#30045, should consider `mergedPrecision` equals zero.

fix: check mergePrecision should consider zero

---

src/InputNumber.tsx
tests/input.test.tsx

fix #305 
fix https://github.com/ant-design/ant-design/issues/29991

fix:keydown when keycode.enter,controlled inputnumber can't flush value

---

src/InputNumber.tsx
tests/decimal.test.tsx
tests/github.test.tsx
tests/input.test.tsx

Fix ant-design/ant-design#30096. I'm not sure whether should trigger `onChange` when `defaultValue` is provided and `changeValue('')` (I think `onChange` should be triggered ?) and I change some original tests. Feel free to close it if it's not reasonable.

fix(onChange): should trigger onChange when removing value

---

src/InputNumber.tsx
tests/input.test.tsx

fix: keydown when tab,inputnumber not trigger onKeyUp

---

docs/examples/simple.tsx
src/InputNumber.tsx
src/utils/MiniDecimal.ts
tests/decimal.test.tsx
tests/github.test.tsx
tests/util.test.tsx

fix https://github.com/ant-design/ant-design/issues/30478

fix: User typing should not block

---

src/InputNumber.tsx
tests/github.test.tsx

fix https://github.com/ant-design/ant-design/issues/30465

fix: User typing should not block input

---

src/InputNumber.tsx
tests/props.test.tsx

To fix  [antd#30873](https://github.com/ant-design/ant-design/issues/30873#issue-912165399). Sync-ed behaviour with  [`Input` component](https://github.com/ant-design/ant-design/blob/ad60e9544cbb8ef9d638e667b8d28cdfac157314/components/input/Input.tsx#L181)

fix: defaultValue wrongly overrode value (antd#30873)

---

docs/examples/formatter.tsx
src/InputNumber.tsx
tests/formatter.test.tsx

额外参数，支持如果发现是用户输入状态就不格式化的操作：
```tsx
<InputNumber<number>
formatter={(num, { userTyping, input }) => {
if (userTyping) {
return input;
}
return String(num);
}}
parser={(num) => Number(num)}
/>
```
ref:  
* https://github.com/ant-design/ant-design/issues/30455   
* https://github.com/ant-design/ant-design/issues/31015

feat: Format support more ability

---

README.md
src/InputNumber.tsx

[#31411](https://github.com/ant-design/ant-design/issues/31411)

feat: add `controls` to  toggle visibility

---

src/InputNumber.tsx
tests/keyboard.test.tsx

resolve https://github.com/ant-design/ant-design/issues/32140

refactor: enter will trigger onChange before form submit

---

src/InputNumber.tsx
src/utils/MiniDecimal.ts
tests/input.test.tsx
tests/util.test.tsx

fix: https://github.com/ant-design/ant-design/issues/33084

fix: should format max/min with precision

---

src/InputNumber.tsx
src/utils/numberUtil.ts
tests/click.test.tsx
tests/keyboard.test.tsx
tests/props.test.tsx

resolve ant-design/ant-design#36077

feat: decuple steps with shift key

---

src/InputNumber.tsx
src/utils/MiniDecimal.ts

Fix type definition of ValueType and InputNumber onChange

---

package.json
src/InputNumber.tsx
tests/github.test.tsx
tests/keyboard.test.tsx

- replace deprecated `KeyboardEvent.which` property with  `KeyboardEvent.key`
- fix bugs link in package.json
- fix typos

refactor: replace deprecated keyboard event prop

---

package.json
src/InputNumber.tsx
tests/__snapshots__/baseInput.test.tsx.snap
tests/baseInput.test.tsx

1. Rc-input-number 引入 BaseInput，这里参考 rc-input, rc-textarea, rc-mentions，把 antd 那里传过来的一些 props 又传到 BaseInput 里了，包括但不限于 addonBefore、addonAfter、prefix。
2. 之前 antd-design 中，addonBefore 等属性没有传到 rc-input-number 里管理，参考 input 做了下调整。

refactor: refactor with Baseinput

---

src/StepHandler.tsx
tests/longPress.test.tsx

fix https://github.com/ant-design/ant-design/issues/43088

fix: solve the issue that input-number's value auto change after fast click step handle in safari

---

src/InputNumber.tsx
src/index.ts

`ValueType` 在 antd 中也引用了，属于幽灵依赖，这里 export 出去让 antd 饮用 input-number 的类型

type: export ValueType

---

.husky/pre-commit
src/InputNumber.tsx
tests/formatter.test.tsx

fix https://github.com/ant-design/ant-design/issues/43641

fix: uncontrolled mode userTyping input not correct

---

docs/demo/simple.tsx
src/InputNumber.tsx
tests/input.test.tsx

resolve https://github.com/react-component/input-number/issues/591

feat: support changeOnBlur

---

src/InputNumber.tsx

In Chrome:
InputNumber.js:431 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

addEventListener('wheel', onWheel) add { passive: false }

---

docs/demo/wheel.tsx
docs/example.md
src/InputNumber.tsx
tests/wheel.test.tsx

`wheel` 重命名为 `changeOnWheel`
并且在 focus 状态才可以触发

refactor: changeOnWheel

---

src/hooks/useCursor.ts
tests/cursor.test.tsx

fix: cursor position when formatter appends characters on empty string
