react-component/input-number

src/InputNumber.js
tests/index.spec.js

Allow input negative symbol

---

package.json
src/InputNumber.js

Close: https://github.com/react-component/input-number/issues/10

chore: add defaultValue for step

---

src/index.js
src/styles.js

- 修复 this._stepUp(Down)Text 未定义；
- 源码中移出样式至 styles 中，方便自定义；
- 部分样式命名规范化；

fix rn bug

---

src/index.js
src/index.web.js
src/mixin.js
tests/index.js

will close #15 and https://github.com/ant-design/ant-design-mobile/issues/91
---
native 的不知道怎么调试，@silentcloud 来同步改下。
> 好像有个 onLongPress 可以用。

auto step when long press

---

src/index.js

https://github.com/ant-design/ant-design/issues/3239

fix: should stop inc/dec after key up

---

package.json
src/mixin.js

- fix: issue #25
- fix: rc-tools run react-native-init  报错

fix: onchange && rn-init error

---

src/mixin.js
tests/index.js

Fix precision of number calculating

---

src/mixin.js
tests/index.js

Follow behavior as https://github.com/hongymagic/react-number-input
close ant-design/ant-design#4265
close ant-design/ant-design-mobile#649
close ant-design/ant-design#2413

input should trigger onChange, and blur to correct value too

---

assets/index.less
src/mixin.js

https://github.com/ant-design/ant-design-mobile/issues/785
ref #42

fix: timeout SPEED is too short, cause infinite loop, ref #42, ant-design/ant-design-mobile#785

---

README.md
examples/custom.html
examples/custom.js
src/index.js

antd-mobile 这边设计师要求用 svg icon 作为加减号的图标， 关联gitlab `#442`

feat: up/down handle support custom element

---

package.json

ref https://github.com/ant-design/ant-design-mobile/issues/959

feat: upgrade rc-tools, avoid waring of pureRenderMixin

---

examples/combination-key-format.js
examples/custom.js
examples/decimal.js
examples/simple.js
examples/small-step.js
package.json
src/InputHandler.js
src/index.ios.js
src/index.js
tests/index.js

https://github.com/ant-design/ant-design/issues/5678

fix prop-types anc createClass

---

src/mixin.js
tests/index.js

fix: input formatter

---

.travis.yml
README.md
examples/precision.js
src/index.js
src/mixin.js
tests/index.js

https://github.com/ant-design/ant-design/issues/5998

support precision

---

src/index.js

feat: add props.id for input element

---

src/mixin.js

change default to max safe integer

---

src/mixin.js
tests/index.js

close  https://github.com/ant-design/ant-design/issues/7358
close https://github.com/ant-design/ant-design/issues/7363

Fix some bugs

---

src/index.js

Down button disabled style when min value or max value be set to 0
This bug also impacted antd and antd-mobile

fixed up button disabled style broken when set min value to 0

---

README.md

Adding onFocus function, it is currently missing from the Readme

Update README.md with onFocus function

---

README.md
src/index.js
tests/index.js

- Adding support for required attr

Fixing Issue #86

---

README.md
src/index.js
tests/index.js

Add pattern prop to InputNumber component

---

src/index.js
tests/index.js

use callbacks to save refs

---

examples/formatter.js
package.json
src/index.js

ref: https://github.com/ant-design/ant-design/issues/11071
1. Record current cursor position before change
2. `componentDidMount` trigger to check the string after origin cursor position
3. move the cursor to the match index
4. If string after cursor not match, provide a degrade logic to do the simple process (This may need more test case from user report)

Adjust cursor logic

---

README.md
src/index.js
tests/index.js

This PR is a revised one of #112

Add decimal separator prop

---

src/index.js
tests/index.js

Closed [issue](https://github.com/ant-design/ant-design/issues/13124)

fix: not completenumber validate

---

package.json
src/index.js

Ref: [#13410](https://github.com/ant-design/ant-design/issues/13410)

Add rest attributes to input

---

src/index.js
tests/index.js

close ant-design/ant-design#13896

Fix onChange(value) from undefined to null

---

src/index.js
tests/index.js

Sometime the value or default value at first time is higher or lower that max  or min, that is little confused, so I add a check function in constructor to avoid this situation.

First render value is in the middle of max and min

---

src/index.js

fix: state should be inited first

---

src/index.js

Fix issue https://github.com/ant-design/ant-design/issues/16710

Fix InputNumber set precision bug

---

src/index.js
tests/index.js

fix https://github.com/ant-design/ant-design/issues/17593

chore: make onBlur sync

---

HISTORY.md
package.json
src/index.js

https://github.com/ant-design/ant-design/issues/9792

refactor: Migrate react lifecycle

---

examples/combination-key-format.js
examples/custom.js
examples/decimal.js
examples/formatter.js
examples/precision.js
examples/simple-use-touch.js
examples/simple.js
examples/small-step.js
src/index.js

https://github.com/react-component/input-number/issues/201

Move role and aria attributes to input from wrapper div to resolve accessibility problem (issue #201)

---

src/index.js
tests/index.js

https://github.com/react-component/input-number/issues/235 - fix

---

src/index.js

may related to ant-design/ant-design#21461

Remove useless e.persist for perfermance

---

src/index.js

close ant-design/ant-design#23732

fix ref.select()

---

src/index.js
tests/index.js

FIX: https://github.com/ant-design/ant-design/issues/24206
改了一下一个精度问题

fix: Decimal over six become scientific notation

---

.gitignore
src/index.js
tests/index.js

Close https://github.com/ant-design/ant-design/issues/24752

fix: bug on long number input

---

src/index.js
tests/index.js

closes: https://github.com/ant-design/ant-design/issues/25614

fix: onBlur should get value '' when clear the data

---

src/InputNumber.tsx
tests/decimal.test.tsx

resolve https://github.com/ant-design/ant-design/issues/29609

fix: Uncontrolled should not format user immediately

---

package.json
src/index.js

https://github.com/ant-design/ant-design/issues/27748
参考 rc-input-number 7.x 进行了一些 hack。

fix: Microsoft Chinese IME input bug

---

docs/demo/debug.md
docs/examples/debug.tsx
src/InputNumber.tsx
tests/github.test.tsx

resolve https://github.com/ant-design/ant-design/issues/32274

fix: Control dynamic change value when user typing should work

---

src/utils/MiniDecimal.ts
tests/util.test.tsx

resolve https://github.com/ant-design/ant-design/issues/32994

fix: negative number should support round

---

src/InputNumber.tsx
src/utils/MiniDecimal.ts
tests/github.test.tsx
tests/util.test.tsx

resolve https://github.com/ant-design/ant-design/issues/36641

fix: Should not always round output value

---

package.json
src/StepHandler.tsx
src/utils/MiniDecimal.ts

type: add type null

---

src/InputNumber.tsx

fix: type error fix

---

package.json
src/InputNumber.tsx
src/index.ts
tests/precision.test.tsx

follow up #507
fix #506
cc @Hoo1nKyoma

fix: Safari of input IME

---

package.json

https://github.com/react-component/util/commit/e59b09c3d06616f7764a345277dfef43b57f98e1
#542
close ant-design/ant-design#41030

chore: bump rc-utils

---

src/InputNumber.tsx
tests/input.test.tsx

close https://github.com/react-component/input-number/pull/540
fix https://github.com/ant-design/ant-design/issues/40733

fix: Input blur with invalidate value should back of validate one and trigger onChange

---

src/InputNumber.tsx
tests/formatter.test.tsx

re create a PR since #347 has conflict for the master
ref:
* https://github.com/ant-design/ant-design/issues/35614
* https://github.com/ant-design/ant-design/issues/31431
close #347

fix: support dynamic formatter

---

src/InputNumber.tsx

close https://github.com/react-component/input-number/security/code-scanning/1

fix: Useless assignment to local variable
